language: rust
sudo: false
rust:
  - stable
  - beta
  - nightly
script: |
  cargo build --verbose &&
  cargo test  --verbose &&
  cargo doc   --verbose
matrix:
  include:
    - rust: nightly-2019-04-19
      before_script:
        - rustup component add rustfmt
        - rustup component add clippy
      script:
        - cargo fmt --all -- --check
        - cargo clippy -- -D clippy::all
cache: cargo
notifications:
  email:
    on_success: never
